:syntax on
set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>
set number
set tabstop=2
set shiftwidth=2
set expandtab
set encoding=utf-8
set hlsearch
set showmatch
set list
set listchars=tab:>.,trail:_,extends:>,precedes:<
set display=uhex
set cursorline

set noswapfile
set autoread

set showmode
set showcmd

augroup cch
  autocmd! cch
  autocmd WinLeave * set nocursorline
  autocmd WinEnter,BufRead * set cursorline
augroup END

hi clear CursorLine
hi CursorLine gui=underline
highlight CursorLine ctermbg=black guibg=black

set lazyredraw
set ttyfast

set laststatus=2
set ruler

set autoindent
set smartindent

scriptencoding utf-8
highlight WhitespaceEOL ctermbg=red guibg=red
match WhitespaceEOL /\s\+$/
