#!/bin/bash

set -e

yum -y install git vim
mkdir tmp
cd tmp
curl -O http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/i386/epel-release-6-8.noarch.rpm
yum install epel-release-6-8.noarch.rpm 
curl -L https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh 
yum -y install patch
yum install gcc-c++
yum -y install zlib-devel
yum -y install readline-devel
yum -y install libyaml-devel
yum -y install libffi-devel
yum -y install openssl-devel
yum -y install make autoconf automake
yum -y install libtool
yum -y install bison
yum -y install libxml2-devel
yum -y install libxslt-devl
yum -y install libxslt-devel
rvm install 2.0.0
